package main

var (
	ListOfItems map[string]interface{} = map[string]interface{}{
		"Bird":             nil,
		"Fish":             nil,
		"Snake":            nil,
		"Spider":           nil,
		"Butterfly":        nil,
		"Hat":              nil,
		"Car":              nil,
		"Bicycle":          nil,
		"Glasses":          nil,
		"Chair":            nil,
		"Spoon":            nil,
		"Fork":             nil,
		"Book":             nil,
		"Leaf":             nil,
		"Tree":             nil,
		"Compass":          nil,
		"Toothpaste":       nil,
		"Fire":             nil,
		"Umbrella":         nil,
		"Guitar":           nil,
		"Candle":           nil,
		"Pizza":            nil,
		"Cloud":            nil,
		"Star":             nil,
		"Anchor":           nil,
		"Skull":            nil,
		"Clock":            nil,
		"Dice":             nil,
		"Cactus":           nil,
		"Camera":           nil,
		"Knife":            nil,
		"Diamond":          nil,
		"Lightbulb":        nil,
		"Television":       nil,
		"Key":              nil,
		"Globe":            nil,
		"Ice cream":        nil,
		"Crown":            nil,
		"Sword":            nil,
		"Balloon":          nil,
		"Flag":             nil,
		"Bow":              nil,
		"Arrow":            nil,
		"Thermometer":      nil,
		"Axe":              nil,
		"Kite":             nil,
		"Piggy bank":       nil,
		"Hourglass":        nil,
		"Magnifying glass": nil,
		"Battery":          nil,
		"Chimney":          nil,
		"Rocket":           nil,
		"Pistol":           nil,
		"Tent":             nil,
		"Window":           nil,
		"Magnet":           nil,
		"Handcuffs":        nil,
		"Fountain":         nil,
		"Cannon":           nil,
		"Cheese":           nil,
		"Skeleton":         nil,
		"Bat":              nil,
		"Teeth":            nil,
		"Bridge":           nil,
		"Tie":              nil,
		"Crab":             nil,
		"Volcano":          nil,
		"Airplane":         nil,
		"House":            nil,
		"Piano":            nil,
		"Door":             nil,
		"Bonfire":          nil,
		"Air balloon":      nil,
		"Worm":             nil,
		"Alien":            nil,
		"Snowman":          nil,
		"Money":            nil,
		"Scissor":          nil,
	}
)
